/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XnemectSurgeonList {
    }
}
declare global {
    interface HTMLXnemectSurgeonListElement extends Components.XnemectSurgeonList, HTMLStencilElement {
    }
    var HTMLXnemectSurgeonListElement: {
        prototype: HTMLXnemectSurgeonListElement;
        new (): HTMLXnemectSurgeonListElement;
    };
    interface HTMLElementTagNameMap {
        "xnemect-surgeon-list": HTMLXnemectSurgeonListElement;
    }
}
declare namespace LocalJSX {
    interface XnemectSurgeonList {
    }
    interface IntrinsicElements {
        "xnemect-surgeon-list": XnemectSurgeonList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xnemect-surgeon-list": LocalJSX.XnemectSurgeonList & JSXBase.HTMLAttributes<HTMLXnemectSurgeonListElement>;
        }
    }
}
